// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// row_scale_dgC
NumericMatrix row_scale_dgC(S4 x, bool center, bool scale, bool add_attr, bool drop_na_rows);
RcppExport SEXP _brathering_row_scale_dgC(SEXP xSEXP, SEXP centerSEXP, SEXP scaleSEXP, SEXP add_attrSEXP, SEXP drop_na_rowsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< S4 >::type x(xSEXP);
    Rcpp::traits::input_parameter< bool >::type center(centerSEXP);
    Rcpp::traits::input_parameter< bool >::type scale(scaleSEXP);
    Rcpp::traits::input_parameter< bool >::type add_attr(add_attrSEXP);
    Rcpp::traits::input_parameter< bool >::type drop_na_rows(drop_na_rowsSEXP);
    rcpp_result_gen = Rcpp::wrap(row_scale_dgC(x, center, scale, add_attr, drop_na_rows));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_brathering_row_scale_dgC", (DL_FUNC) &_brathering_row_scale_dgC, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_brathering(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
