# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

row_scale_dgC <- function(x, center = TRUE, scale = TRUE, add_attr = TRUE, drop_na_rows = TRUE) {
    .Call('_brathering_row_scale_dgC', PACKAGE = 'brathering', x, center, scale, add_attr, drop_na_rows)
}

